name: Deploy to Server

on:
  push:
    branches: [ main ]  # Change to your default branch if different
  workflow_dispatch:    # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/checkmylinks
          git pull origin main
          systemctl restart checkmylinks.service
          systemctl status checkmylinks.service